"""empty message

Revision ID: 3ce567c2d944
Revises: 
Create Date: 2025-02-14 19:19:58.921202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce567c2d944'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'purchase_order', 'user', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_order', type_='foreignkey')
    op.drop_column('purchase_order', 'created_by_id')
    # ### end Alembic commands ###
